language: python

env:
  - TORNADO_VERSION=''
  - TORNADO_VERSION='>=3.0,<4.0'

install:
 - python setup.py sdist
 - pip install tornado$TORNADO_VERSION
 - pip install dist/finch-`python setup.py --version`.tar.gz
 - pip install -r test-requirements.txt

script:
 - nosetests tests/unit
