language: python

install:
 - python setup.py sdist
 - mkdir tmp
 - tar xvf dist/finch-*.tar.gz -C tmp
 - python tmp/finch-*/setup.py install

 - pip install -r requirements-devel.txt --use-mirrors --upgrade

script:
 - nosetests tests/unit
